### ISSUE TITLE
App crashed when trying to select word

### ISSUE THREAD

**Issue by ghost** [billthefarmer/crossword#1]
**Expected Behaviour**

One should be able to select the word, or the UI should be refreshed, so the word could not be selected.

<br>
<hr>

**Actual Behaviour**

When one chooses a certain number of letters, let's say 7.

Immediately after that, one changes into another number, let's say 14.

Selecting the word will crash the app. 

<br>
<hr>

**Steps to reproduce**

Launch Crossword on Android 8.0.0

Choose a certain number of letters, let's say 7.

Change the number of letters into another number, let's say 14.

Select any word at all.

<br>
<hr>

**Testing Environment**

Device: Honor 8 Pro

Model number: DUK-L09

OS: Android 8.0.0

App Version: 1.06

*Notes: App downloadable on F-droid* 

<br>
<hr>

**Recording of bug**

https://youtu.be/fkokElmY0Hk

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mrplokmi/app-crashed-when-trying-to-select-word">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by billthefarmer** [comment]
This will be fixed in the next version.
