### ISSUE TITLE
WebView scroll position lost after device rotation

### ISSUE THREAD

**Issue by calbee633810** [billthefarmer/crossword#2]
Steps to reproduce
1. search a word
2. Click a word in the list to open WebView
3. scroll WebView
4. Rotate screen

WebView scroll position should persist after device rotation, however, it scroll back to top after rotation. It's annoying because user has to manually scroll to it expected position after rotation

![screen shot 2018-04-13 at 1 01 46 pm](https://user-images.githubusercontent.com/38213896/38717662-e1a5b3fe-3f1a-11e8-94c9-e97fd008a515.png)
Screenshot before rotation

![screen shot 2018-04-13 at 1 01 55 pm](https://user-images.githubusercontent.com/38213896/38717672-e79319f0-3f1a-11e8-85bc-7105905e3155.png)
Screenshot after rotation

**Comment by billthefarmer** [comment]
This will be fixed in next release.
