### ISSUE TITLE
A confusing icon on "Crossword" 's UI

### ISSUE THREAD

**Issue by b450mhdv** [billthefarmer/crossword#5]
@billthefarmer 

Hello, I found a problem with the app's UI design. At first sight, the widget at the top of the homepage looks like a "Message", and I thought it is related to sending messages. When I clicked on it, it took me to a new page for searching phrases. Although this icon seems to have something to do with "phrase", I think the function of this icon is different from the common "Message" icon I saw in other popular apps. As a suggestion, if you can design a more intuitive icon, it may greatly improve the user experience. Could you fix this issue?

![Crossword (1)](https://user-images.githubusercontent.com/78015408/128508756-993960f3-ee16-47ee-9acd-7d4a7580c511.png) ![Crossword (2)](https://user-images.githubusercontent.com/78015408/128508762-0acc07d6-a84a-449e-b108-75d103c0ebbd.png)

**Comment by billthefarmer** [comment]
What are the chances of a crossword solving app sending messages?
You obviously didn't bother to read the README…

> There are three icons in the toolbar: **Anagram**, which will show the
anagram screen, **Help**, which will show the help screen, and
**About**, which will show the copyright, licence and version.

Or the app built in help…

![Screenshot_20210806-144444 1](https://user-images.githubusercontent.com/3448386/128520593-597f27f9-b1f3-4bb5-96c2-cc2a8ed28668.png)

Or a long touch on the icon…

![Screenshot_20210806-144403 1](https://user-images.githubusercontent.com/3448386/128520777-8f06df31-766e-40a3-b6b1-4ada590227cc.png)
