### ISSUE TITLE
Contains function

### ISSUE THREAD

**Issue by sttrebo** [billthefarmer/crossword#6]
Hi
Is there any thoughts of adding an option to search for words that contain different letters?  For example, 6 letter word, ends in 't' and contains an 'e' or contains an 'e' and a 'r' kind of thing?

Thanks

**Comment by billthefarmer** [comment]
I will investigate... OK, that works, it will be in the next version.

![Screenshot_20220517-161543 1](https://user-images.githubusercontent.com/3448386/168856416-546fb77e-77f1-423d-801a-7d3e22fe1c80.png)

**Comment by sttrebo** [comment]
sweet, thank you...
