### ISSUE TITLE
[Feature Request] Launch via Intents

### ISSUE THREAD

**Issue by yourealwaysbe** [billthefarmer/crossword#7]
I was thinking about integrating the solver with [Forkyz](https://gitlab.com/Hague/forkyz). For this the solver would need to recognise some intent for launch with a pattern for a word search or anagram letters.

Then Forkyz could have some option to get help via the solver. It would send the intent for word search or anagram with the data, and the crossword solver would open to the right page.

Let me know what you think. Happy to help implement when I have time.

**Comment by billthefarmer** [comment]
This is possible, I have already done something similar with my [Siggen](https://github.com/billthefarmer/sig-gen) app. I would suggest using an intent with ACTION_VIEW and EXTRA_TEXT. The text would be a string with dots for unknown letters. The app would set the word size to the length of the string, insert the letters and do a search. Optionally a second string with position unknown letters could be appended with a delimiter. I haven't tried any of this, I will test it and add it if it works.

**Comment by billthefarmer** [comment]
OK, that seems to work...
```shell
$ adb shell am start -e android.intent.extra.TEXT bill....,d  -n org.billthefarmer.crossword/.Main
Starting: Intent { cmp=org.billthefarmer.crossword/.Main (has extras) }
Warning: Activity not started, its current task has been brought to the front
```
![Screenshot_20231119-142331 1](https://github.com/billthefarmer/crossword/assets/3448386/6f8aa13f-d6d5-4ce4-be8a-f7df4a1ec4a6)

You can also do it by sharing text That will be in the next version.

**Comment by yourealwaysbe** [comment]
Nice -- thanks. I'll have a play and make use of that in the next version of Forkyz. I'll close this and reopen if there are any problems.

**Comment by yourealwaysbe** [comment]
[Works well, thanks!](https://gitlab.com/Hague/forkyz/-/commit/712e7fe9ca8e0546fd3bc8597c54b164181a034d)
